// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCoreLecture.Model;

#nullable disable

namespace WebApiCoreLecture.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20230304134701_desig")]
    partial class desig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiCoreLecture.Model.HRModel.EmployeeModel.TblCostCenter", b =>
                {
                    b.Property<long>("IntCostCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntCostCenterId"));

                    b.Property<DateTime>("DteLastActionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DteServerDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("IntAccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("IntActionBy")
                        .HasColumnType("bigint");

                    b.Property<long>("IntBusinessUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("IntControllingUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("IntCostCenterGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("IntCostCenterTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("IntProfitCenterId")
                        .HasColumnType("bigint");

                    b.Property<long>("IntResponsiblePersonId")
                        .HasColumnType("bigint");

                    b.Property<long>("IntSbuid")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StrCostCenterCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrCostCenterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntCostCenterId");

                    b.ToTable("TblCostCenter");
                });

            modelBuilder.Entity("WebApiCoreLecture.Model.HRModel.EmployeeModel.TblCountry", b =>
                {
                    b.Property<long>("IntCountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntCountryId"));

                    b.Property<DateTime>("DteLastActionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DteServerDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("IntActionBy")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StrCountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrCountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDialingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntCountryId");

                    b.ToTable("TblCountry");
                });

            modelBuilder.Entity("WebApiCoreLecture.Model.HRModel.EmployeeModel.TblDistrict", b =>
                {
                    b.Property<long>("IntDistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntDistrictId"));

                    b.Property<DateTime>("DteLastActionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DteServerDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("IntActionBy")
                        .HasColumnType("bigint");

                    b.Property<long>("IntCountryId")
                        .HasColumnType("bigint");

                    b.Property<long>("IntDivisionId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StrDistrictGeocode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntDistrictId");

                    b.ToTable("TblDistrict");
                });

            modelBuilder.Entity("WebApiCoreLecture.Model.HRModel.EmployeeModel.TblDivision", b =>
                {
                    b.Property<long>("IntDivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntDivisionId"));

                    b.Property<long>("IntCountryId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StrCountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDivision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDivisionGeocode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDivitionBanglaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntDivisionId");

                    b.ToTable("TblDivision");
                });

            modelBuilder.Entity("WebApiCoreLecture.Model.HRModel.EmployeeModel.TblEducationDegree", b =>
                {
                    b.Property<long>("IntEducationDegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntEducationDegreeId"));

                    b.Property<long>("IntLevelOfEducationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StrEducationDegree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrLevelOfEducation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntEducationDegreeId");

                    b.ToTable("TblEducationDegree");
                });

            modelBuilder.Entity("WebApiCoreLecture.Model.HRModel.EmployeeModel.TblEmployeeBasicInfo", b =>
                {
                    b.Property<long>("IntEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntEmployeeId"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ActionBy")
                        .HasColumnType("bigint");

                    b.Property<string>("AlternativeContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("BloodGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BusinessunitId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CostCenterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DesignationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EmpGradeId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EmploymentStatusId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EmploymentTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Idnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IdtypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineManagerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LineManagerId")
                        .HasColumnType("bigint");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<string>("PresentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Sbuid")
                        .HasColumnType("bigint");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkplaceGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkplaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("strEmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntEmployeeId");

                    b.ToTable("TblEmployeeBasicInfos");
                });

            modelBuilder.Entity("WebApiCoreLecture.Model.HRModel.EmployeeModel.TblEmployeeDepartment", b =>
                {
                    b.Property<long>("IntDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntDepartmentId"));

                    b.Property<DateTime?>("DteLastActionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DteServerDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IntAccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("IntActionBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("IntBusinessUnitId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCorporate")
                        .HasColumnType("bit");

                    b.Property<string>("StrDepartmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntDepartmentId");

                    b.ToTable("TblEmployeeDepartment");
                });

            modelBuilder.Entity("WebApiCoreLecture.Model.HRModel.EmployeeModel.TblEmployeeDesignation", b =>
                {
                    b.Property<long>("IntDesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntDesignationId"));

                    b.Property<DateTime?>("DteLastActionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DteServerDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IntAccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("IntActionBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("IntBusinessUnitId")
                        .HasColumnType("bigint");

                    b.Property<long?>("IntPosionId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsManagement")
                        .HasColumnType("bit");

                    b.Property<string>("SrtPositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDesignationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrDesignationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntDesignationId");

                    b.ToTable("TblEmployeeDesignation");
                });

            modelBuilder.Entity("WebApiCoreLecture.Model.TblDesignation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("TblDesignation");
                });

            modelBuilder.Entity("WebApiCoreLecture.Model.TblEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DesignationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Doj")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<int>("IsMarried")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TblEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
